# Site settings
title: "SNU PI Lab"
email: your-email@domain.com
description: "SNUPI Laboratory, Seoul National University"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yj-yu.github.io/snupi_home" # the base hostname & protocol for your site
favicon: /images/favicon.png

include: ['_people', '_projects', '_teachings', '_gallery', '_news']
collections:
  people:
    output: false
  publications:
    output: false
  teachings:
    output: false
  gallery:
    output: false
  news:
    output: false

# Lab Info.
# Postal address (add as many lines as necessary)
address:
  - line: SNUPI Lab. Computer Science and Engineering, Seoul National University
  - line: (address), Republic of Korea
  - line: Room 419, 302 Building
  - line: "TEL: +82-02-880-xxxx"

github_username:  yjyu

# Build settings
markdown: kramdown

# Gems
gems: [jekyll-paginate]

# Jekyll pagination
paginate: 8
paginate_path: "news/page:num"

defaults: 
  - scope:
      path: "people/dongjookim.html"
    values:
      sitemap: false
