# Site settings
title: "SNU PI Lab"
email: your-email@domain.com
description: "SNUPI Laboratory, Seoul National University"
baseurl: "" #"/snupi_home" # the subpath of your site, e.g. /blog/
url: "https://pi.snu.ac.kr" # the base hostname & protocol for your site
favicon: /images/favicon.png

include: ['_people', '_projects', '_teachings', '_gallery', '_news']
collections:
  people:
    output: false
  publications:
    output: false
  teachings:
    output: false
  gallery:
    output: false
  news:
    output: true
    permalink: /news/:categories/:year/:month/:day/:slug.html

# Lab Info.
# Postal address (add as many lines as necessary)
address:
  - line: SNUPI Lab. Computer Science and Engineering, Seoul National University
  - line: (address), Republic of Korea
  - line: Room 319, 302 Building
  - line: "TEL: +82-02-880-8455"

github_username:  yjyu

# Build settings
markdown: kramdown

# Gems
gems: [jekyll-paginate]

# Jekyll pagination (Note: jekyll-paginate only works with _posts, not custom collections like _news)
# Currently not used - news.html uses site.news collection instead
# paginate: 8
# paginate_path: "news/page:num"

defaults: 
  - scope:
      path: "people/dongjookim.html"
    values:
      sitemap: false
